version: "3.5"

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath ./data -sharedDb
    volumes:
      - ./dynamodb-local:/home/dynamodblocal/data
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
  node:
    image: node:12
    command: bash -c 'npm install && npm run start'
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    environment:
      - STORAGE_SUTEUOMESSAGING_NAME=suteuomessaging
      - ENDPOINT_OVERRIDE=http://dynamodb:8000
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 3001:8080
    environment:
      - API_URL=http://localhost:3000/api-docs.json
